# Generated by Django 2.2 on 2019-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
